SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

BEGIN
CREATE TABLE [dbo].[CompletedGoals](
	[Id] [uniqueidentifier] NOT NULL,
	[Points] int NOT NULL,
	[Reason] VARCHAR(100) NOT NULL,
  CONSTRAINT [PK_CompletedGoals_Id] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Goals](
	[Id] [uniqueidentifier] NOT NULL,
	[Points] int NOT NULL,
	[Target] int NOT NULL,
	[Reason] VARCHAR(100) NOT NULL,
  CONSTRAINT [PK_Goals_Id] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END

GO