SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Transaction]') AND type in (N'U'))
BEGIN

CREATE TABLE [dbo].[Transaction](
	[Id] int NOT NULL,
	[Amount] decimal(5,2) NOT NULL,
	[Category] varchar(50) NOT NULL,
	[Updated] [datetime] NOT NULL,
  CONSTRAINT [PK_Transaction_Id] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END

GO